name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: cargo clippy
      - name: Build
        run: cargo deb --verbose
      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: regexpr
          path: target/debian/regexpr_*.deb
          if-no-files-found:
            error: "Could not find .deb package output"
